# Profil docker uniquement — ne pas mélanger avec localhost du fichier principal
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

proposal.feign.project-url=http://project-service:8091/freelance
proposal.feign.user-url=http://user-service:5088/api

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/Job_Board_Realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://host.docker.internal:8180/realms/Job_Board_Realm/protocol/openid-connect/certs
